import Foundation
import IRIKit

/// A generated ontology term declaration.
///
/// `OntologyTerm` is the base protocol for all generated term types.
/// It defines the core identity: what a term IS.
///
/// Specific capabilities are added through contribution protocols
/// (`LabeledTerm`, `CommentedTerm`, `TypedTerm`, etc.) that compute
/// properties from the `children` array.
///
/// ContentModifiers are the meta layer — they're applied to term
/// declarations in the DSL, and the macro reads them to generate
/// the appropriate protocol conformances on the output type.
///
///     // Generated by @Vocabulary:
///     extension OWL {
///         struct ThingTerm: OntologyTerm, LabeledTerm, CommentedTerm, TypedTerm {
///             let name = "Thing"
///             let iri = IRI("http://www.w3.org/2002/07/owl#Thing")
///             let kind: TermKind = .class
///             let children: [any Node]
///         }
///     }
///
///     // Usage:
///     OWL.Thing           // The Thing declaration
///     OWL.Thing.iri       // IRI identity
///     OWL.Thing.name      // "Thing"
///     OWL.Thing.label     // "Thing" — computed from children
///     OWL.Thing.comment   // "The class of OWL individuals." — computed from children
public protocol OntologyTerm: Sendable, Identifiable, Equatable, Subject, Predicate, Object {

    /// The declared term name (e.g., "Thing", "sameAs").
    var name: String { get }

    /// The IRI identity for this term.
    ///
    /// This is the identity — how you identify the term.
    /// It's not the term itself; the term is the full declaration.
    var iri: IRI { get }

    /// The kind of term (class, property, individual, datatype).
    var kind: TermKind { get }

    /// The raw annotation children from the DSL declaration.
    ///
    /// Contribution protocols compute their properties from this array.
    /// The macro generates this from the DSL body's trailing closure.
    var children: [any Node] { get }
}

// MARK: - Identifiable Conformance

extension OntologyTerm {
    public var id: IRI { iri }
}

// MARK: - Equatable Conformance

extension OntologyTerm {
    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.iri == rhs.iri
    }
}

// MARK: - Convenience

extension OntologyTerm {

    /// Whether this term is an RDF class declaration.
    public var isClass: Bool { kind == .class }

    /// Whether this term is an RDF property declaration.
    public var isProperty: Bool { kind == .property }

    /// Whether this term is an RDF individual declaration.
    public var isIndividual: Bool { kind == .individual }

    /// Whether this term is an RDF datatype declaration.
    public var isDatatype: Bool { kind == .datatype }
}
