schemaVersion: 1
enabledWorkflows:
  - swift-package
  - xcode-ide
debug: false
sentryDisabled: true
setupPreferences:
  platforms:
    - macOS
sessionDefaults:
  workspacePath: .swiftpm/xcode/package.xcworkspace
  scheme: RDFKit-Package
